import 'package:soundboard/src/util/quote.dart';

const List<Quote> ALL_QUOTES = [
  Quote("test_sound", "test sound"),
  Quote("jonas_mn_knieen_doen_pijn", "M'n knieën doen pijn"),
  Quote("jonas_simon_kun_je_stoppen", "Simon, kun je alsjeblieft stoppen"),
  Quote("jonas_allahu_akbar", "Allahu akbar"),
  Quote("jonas_je_bent_zo_een_hoer_he_simon", "Je bent zo een hoer"),
  Quote("jonas_hoper", "Hoper"),
  Quote("jonas_koekoek", "Koekoek"),
  Quote("jordy_wa_ne_kutjood", "Wa ne kutjood"),
  Quote("jordy_de_kopkes_zijn_weer_gaan_rollen", "De kopkes zijn weer gaan rollen"),
  Quote("jordy_deze_kleine_dwerg", "Deze kleine dwerg wil bloed zien"),
  Quote("michiel_abonneren", "Abonneren"),
  Quote("michiel_dit_is_ons_motto", "Dit is ons motto"),
  Quote("michiel_slavenarbeid", "Slavenarbeid"),
  Quote("michiel_het_leven_in_de_mijn", "Het leven in de mijn"),
  Quote("mathias_wil_je_mn_huis_zien", "Wil je m'n huis zien?"),
  Quote("mathias_hou_je_niet_zoveel_van_vechten", "Hou je niet zoveel van vechten?"),
  Quote("mathias_sla_ze_van_de_rampard", "Sla ze van de rampards"),
  Quote("mathias_ik_word_hier_misselijk_van", "Ik word hier misselijk van"),
  Quote("mathias_blugh", "BLUGH"),
  Quote("simon_thordor_is_gevallen", "Thordor is gevallen"),
  Quote("simon_hier_op_uw_bek", "Hier, op uw bek"),
  Quote("simon_dit_meen_je_niet", "Dit meen je niet"),
  Quote("simon_vettige_apenkoppen", "Vettige apenkoppen"),
];