name: Create Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release Version'
        required: true
        
permissions:
  contents: write

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --target=lib/src/main.dart

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release-{{ github.event.inputs.release_version }}.apk
          
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          files: |
            build/app/outputs/flutter-apk/app-release-{{ github.event.inputs.release_version }}.apk
          tag_name: ${{ github.event.inputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
